a = input("Digite algo: ")
print(f"O tipo primitivo de {type(a)}")
print(f"Só tem espaços {a.isspace()}")
print(f"Só tem números {a.isnumeric()}")
print(f"Só tem letra {a.isalpha()}")
print(f"Alfanumérico {a.isalnum()}")
print(f"Só tem minúsculas {a.islower()}")
print(f"Só tem maiusculas {a.isupper()}")
print(f"Capitalizada {a.istitle()}")
print("O que vc digitou: {}" .format(a))
